version: "3.8"
services:
  frontend:
    build: ./client01
    ports:
      - "80:80"
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
volumes:
  mongodb_data: {}
