name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies and Run tests in client01
        run: |
          cd client01
          npm install
          npm test

      - name: Build client01
        run: |
          cd client01
          npm run build

      - name: Build server
        run: |
          cd server
          npm run build
